name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from
    paths:
        - 'backend/**'  # Change this to the path of your backend code

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package the function
      run: zip -r michaelBackend.zip index.js

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1  # Change this to your AWS region

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name michaelBackend \
          --zip-file fileb://michaelBackend.zip
